# Generated by Django 5.1.4 on 2024-12-23 14:22

from django.contrib.auth.models import User
from django.db import migrations, models


def create_superuser(apps, schema_editor):
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='123'
        )


def delete_superuser(apps, schema_editor):
    User.objects.get(username='admin').delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id',
                 models.UUIDField(help_text='Unique identifier for the property', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(help_text='Parcel Identification Number')),
                ('lotarea', models.IntegerField(help_text='Lot size in square feet')),
                ('overallqual', models.IntegerField(help_text='Overall material and finish quality')),
                ('overallcond', models.IntegerField(help_text='Overall condition rating')),
                ('centralair', models.BooleanField(help_text='Central air conditioning (True/False)')),
                ('fullbath', models.IntegerField(help_text='Full bathrooms above grade')),
                ('bedroomabvgr', models.IntegerField(help_text='Number of bedrooms above basement level')),
                ('garagecars', models.IntegerField(blank=True, help_text='Size of garage in car capacity', null=True)),
                ('saleprice', models.IntegerField(help_text='Sale price (in USD)')),
                ('data_source', models.IntegerField(default=1, help_text='1=Ames, 2=User provided')),
                ('dataset',
                 models.CharField(choices=[('training', 'Training'), ('validation', 'Validation'), ('test', 'Test')],
                                  default='training', max_length=10)),
            ],

            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
