# Generated by Django 5.1.4 on 2024-12-23 12:46
from django.contrib.auth.models import User
from django.db import migrations


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='123'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
