# Generated by Django 5.1.4 on 2024-12-27 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_load_ames_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bldgtype',
            field=models.CharField(blank=True, help_text='Type of dwelling', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition1',
            field=models.CharField(blank=True, help_text='Proximity to main road or railroad', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition2',
            field=models.CharField(blank=True, help_text='Proximity to main road or railroad (if a second exists)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='data_source',
            field=models.IntegerField(default=1, help_text='1=Ames, 2=Verified Sale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='enclosedporch',
            field=models.IntegerField(blank=True, help_text='Enclosed porch area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='extercond',
            field=models.CharField(blank=True, help_text='Condition of exterior material', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='exterior1st',
            field=models.CharField(blank=True, help_text='Exterior covering on house', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='exterior2nd',
            field=models.CharField(blank=True, help_text='Exterior covering on house (if more than one)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='exterqual',
            field=models.CharField(blank=True, help_text='Quality of exterior material', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='fireplaces',
            field=models.IntegerField(blank=True, help_text='Number of fireplaces', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='firstflrsf',
            field=models.IntegerField(blank=True, help_text='First floor square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='foundation',
            field=models.CharField(blank=True, help_text='Type of foundation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='functional',
            field=models.CharField(blank=True, help_text='Home functionality (assume typical unless deductions are warranted)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='garagecars',
            field=models.IntegerField(default=0, help_text='Size of garage in car capacity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='grlivarea',
            field=models.IntegerField(blank=True, help_text='Above grade (ground) living area square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='halfbath',
            field=models.IntegerField(blank=True, help_text='Half baths above grade', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=models.CharField(blank=True, help_text='Type of heating', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='heatingqc',
            field=models.CharField(blank=True, help_text='Heating quality and condition', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='housestyle',
            field=models.CharField(blank=True, help_text='Style of dwelling', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the property', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchenabvgr',
            field=models.IntegerField(blank=True, help_text='Number of kitchens', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchenqual',
            field=models.CharField(blank=True, help_text='Kitchen quality', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='landcontour',
            field=models.CharField(blank=True, help_text='Flatness of the property', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='landslope',
            field=models.CharField(blank=True, help_text='Slope of property', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lotconfig',
            field=models.CharField(blank=True, help_text='Lot configuration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lotshape',
            field=models.CharField(blank=True, help_text='General shape of property', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lowqualfinsf',
            field=models.IntegerField(blank=True, help_text='Low quality finished square feet (all floors)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='miscval',
            field=models.IntegerField(blank=True, help_text='Value of miscellaneous feature', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='mosold',
            field=models.IntegerField(blank=True, help_text='Month sold', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='mssubclass',
            field=models.IntegerField(blank=True, help_text='The building class', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='mszoning',
            field=models.CharField(blank=True, help_text='General zoning classification', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Physical location within Ames', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='openporchsf',
            field=models.IntegerField(blank=True, help_text='Open porch area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pid',
            field=models.IntegerField(blank=True, help_text='Parcel Identification Number', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='poolarea',
            field=models.IntegerField(blank=True, help_text='Pool area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='roofmatl',
            field=models.CharField(blank=True, help_text='Roof material', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='roofstyle',
            field=models.CharField(blank=True, help_text='Type of roof', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='salecondition',
            field=models.CharField(blank=True, help_text='Condition of sale', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='saletype',
            field=models.CharField(blank=True, help_text='Type of sale', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='screenporch',
            field=models.IntegerField(blank=True, help_text='Screen porch area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='secondflrsf',
            field=models.IntegerField(blank=True, help_text='Second floor square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, help_text='Type of road access', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='threessnporch',
            field=models.IntegerField(blank=True, help_text='Three season porch area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='totrmsabvgrd',
            field=models.IntegerField(blank=True, help_text='Total rooms above grade (excluding bathrooms)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='utilities',
            field=models.CharField(blank=True, help_text='Type of utilities available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='wooddecksf',
            field=models.IntegerField(blank=True, help_text='Wood deck area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yearbuilt',
            field=models.IntegerField(blank=True, help_text='Original construction date', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yearremodadd',
            field=models.IntegerField(blank=True, help_text='Remodel date (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yrsold',
            field=models.IntegerField(blank=True, help_text='Year sold', null=True),
        ),
    ]
