# Generated by Django 5.1.4 on 2024-12-28 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_bldgtype_alter_property_condition1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='User-provided basic description of the best features of the property')),
                ('generated_text', models.TextField(help_text='LLM-generated salesy listing for the property')),
                ('feedback_score', models.FloatField(blank=True, help_text='Score for RLHF (e.g., 1 for thumbs up, -1 for thumbs down)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property')),
            ],
        ),
    ]
